In [3]:
import tensorflow as tf
input  = tf.ones([1, 4, 4, 1])
filter = tf.ones([3, 3, 1, 1])
output = tf.nn.conv2d(input, filter, [1, 1, 1, 1], 'SAME')


In [4]:
output

<tf.Tensor 'Conv2D:0' shape=(1, 4, 4, 1) dtype=float32>

In [5]:
import numpy as np
grad_output = np.ones((1, 4, 4, 1), dtype=np.float32)
grad_output[0, 1, 1, 0] = 1       # Selecvt gradients you care for.
print grad_output.reshape((4,4))
grads = tf.gradients(output, input, grad_output)
sess = tf.Session()
print sess.run(grads[0]).reshape((4,4))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 4.  6.  6.  4.]
 [ 6.  9.  9.  6.]
 [ 6.  9.  9.  6.]
 [ 4.  6.  6.  4.]]
